- main.go
This just multiplies the Seconds by 1000, to ensure Grafana can format the epoch label properly with this https://github.com/grafana/grafana/pull/14510 which assumes the epoch is in milliseconds.
> convert epoch to milliseconds

- Gopkg.lock
- main.go
- vendor/k8s.io/helm/pkg/tlsutil/cfg.go
- vendor/k8s.io/helm/pkg/tlsutil/tls.go
- vendor/k8s.io/helm/pkg/urlutil/urlutil.go
Tiller may be configured to only accept TLS connections from clients with a valid known certificate. This PR adds the possibility to specify and use a TLS client cert in helm-exporter to successfully connect to such tiller instances.
The helm-exporter can be configured with the newly added command line flags `tiller-tls-enable`, `tiller-tls-key-path` and `tiller-tls-cert-path`.
> Add support for TLS connections to tiller

- Dockerfile
Image `0.4.1` fails with:
```
linux spec user: unable to find user helm-exporter: no matching entries in passwd file
```
> Add helm-exporter user in Dockerfile

- main.go
With original code exporter always lists releases in current configured namespace
> Fixed connection to namespace

- helm/README.md
- helm/templates/deployment.yaml
- helm/values.yaml
- main.go
Recent versions of Grafana (I am testing with v6.7.1) have a "Series value as timestamp" option which can be used with the timestamp option implemented in this PR, in order to use the helm_chart_info metric for Grafana annotations pulled from Prometheus.
https://grafana.com/docs/grafana/latest/reference/annotations/#querying-other-data-sources
> Add option to set the value to helm release's timestamp

- helm/templates/configmap.yaml
The helm chart cannot be applied without this PR due to wrong indentation of labels in the ConfigMap template.
> Fix the ConfigMap template's indentation

- helm/templates/deployment.yaml
`args` was duplicated and `-config` was given in the (old?) `--config` variant.
> Fix duplicate args in Helm chart

- helm/README.md
- helm/templates/deployment.yaml
- helm/values.yaml
- main.go
Fetching all upstream latest chart versions can be problematic in large cluster deploys. The feature is also less helpful in its current from when using a large number of private charts/repositories.
> Make fetching the latest chart version configurable

- go.sum
- main.go
We have an issue in our cluster with around 100 releases: the exporter takes too long to compute metrics on the fly (around 15 to 20 seconds) which is above the 10s timeout of prometheus.
I propose to fetch data from the cluster in the background, every 30 seconds, to void computing them on the fly and expose current metrics values on the `/metrics` endpoint.
It uses mutex to properly switch data (the beginning of `runStats` is a `Reset` so if metrics request come in the middle of the refresh, it's broken).
The only drawback when used without the `namespace` flag: during the first 30s there is no data (the `go informer()` has not yet finished but the `runStats` starts...) It's only the first 30s on cold start, I think it's ok. Let me know what you think about it.
Before the change, on a …
> Execute runStats in background to avoid timeout when done synchronously

- helm/templates/deployment.yaml
- helm/values.yaml
Hello,
there are cases when you want to explicitly set additional podLabels without introducing any changes to already managed resources (selectorLabels).
> Allow for podLabels to be set

- registries/helm_hub.go
The HTTP request in `getChartVersions` redirects to `https://artifacthub.io/api/chartsvc/v1/charts/%s` which doesn't return a JSON structure and instead returns a 200 with a HTML response causing a [parsing error](https://github.com/sstarcher/helm-exporter/issues/56).
Based on the Artifact Hub API [documentation](https://artifacthub.github.io/hub/api/?urls.primaryName=Artifact%20Hub%20API) this PR updates the request URL and also the parses the new JSON response structure.
Note: the HTTP request in `findChart` results in a redirect to `https://artifacthub.io/api/chartsvc/v1/charts/search?q=%s` which is still a valid [API](https://artifacthub.github.io/hub/api/?urls.primaryName=Monocular%20compatible%20search%20API#/Monocular/get_api_chartsvc_v1_charts_search)
> Address changes to artifacthub API

- helm/templates/tests/test-connection.yaml
This sets the test to connect to correct /healthz endpoint, resulting in a HTTP 200 OK response code and will mark the test as successful.
Added hook hook-delete-policy to remove/cleanup the test pod if the test is successful (so subsequent test run won't encounter the error `warning: Hook test helm-exporter/templates/tests/test-connection.yaml failed: pods "helm-exporter-test-connection" already exists`
Fixes https://github.com/sstarcher/helm-exporter/issues/58
> Optimize test-connection

- helm/README.md
- helm/templates/service.yaml
Fixes #62.  Allows custom replacement for `prometheus.io/scrape: "true"` annotation.
> Added support for custom service scrape-enable annotation

- registries/helm_hub.go
Change the URL from hub.helm.sh to artifacthub.io so we can skip the redirection
Add the agent to fix https://github.com/sstarcher/helm-exporter/issues/64
It seems only this endpoint requires a user agent.
> Add agent for request to artifacthub.io/api/chartsvc

- helm/templates/ingress.yaml
I believe the latest versions of the chart are broken (1.1.0 and 1.0.1 both seem affected) due to `backend` in the ingress not matching the `networking.k8s.io/v1` API spec; I've been receiving the following error on creating a release:
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "serviceName" in io.k8s.api.networking.v1.IngressBackend, ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "servicePort" in io.k8s.api.networking.v1.IngressBackend]
```
See https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource and https://blog.hycorve.com/migrating-from-ingress-networking-k8s-io-v1beta1-to-v1/
I …
> Update ingress to suit networking.k8s.io/v1

- README.md
- example_conf.yaml
- go.mod
- go.sum
- helm/values.yaml
- main.go
- registries/charts.go
- registries/helm_index.go
fixes: #41 
This PR introduce the basic auth of private helm registries via the helm sdk. Now, you dont need to transform the index.yaml anymore. The helm sdk takes care to return the latest version.
> feat: Adding Basic Auth to access Helm repo

- helm/README.md
- helm/templates/deployment.yaml
- helm/templates/servicemonitor.yaml
- helm/values.yaml
helm-exporter might be slow to start on clusters with a relatively large number of namespaces, that might cause a crashloop. Custom probe configuration totally fixes it.
> Make deployment probes configurable

- main.go
- registries/helm_hub.go
When fetchLatest is false, we don't need the background job to update artifacthub cache every hour.
> disable update artifacthub cache when fetchLatest is false

- helm/templates/deployment.yaml
- helm/values.yaml
- main.go
Added release status as a string to the metric as additional label.
This addition was needed because with the current implementation, the encoded status as value, it's nearly impossible and extremely complicated (at least for me with my knowledge on Grafana and PromQL) to be able to count and breakdown by the status of the Helm charts.
With this addition we are able to have clear overview of the state of our Helm releases and visualize them in Grafana. 
Our idea was to be notified if we have a release which is stuck in a "bad" state for a certain time and now we're able to to do it.
I think the resource footprint on Prometheus would be really negligible since this label has really low (predefined) cardinality.
> Added Release status as a label to the metric

- README.md
url change by https://grafana.com/grafana/dashboards/9367-helm-exporter/  before change https://grafana.com/grafana/dashboards/9367 --> 404
> Update url to grafana dashboard

- main.go
It should fix the problem when you do not need to enable all types of metrics.
Without it if you disable one of **"info-metric"|"timestamp-metric"|"outdated-metric"**
you will get this error.
`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x103d77460]
`
Thanks!
> Add bool conditions

- main.go
Thanks for the exporter :)
We are going to change to way how we collect metrics by using the `interval-duration` set more or less every few hours. Unfortunately for the initial metrics, we have to wait for `interval-duration`, because there are no `clients` collected at the initial run stats.
> fix: wait for the clients before starting to collect metrics when using the interval-duration option

- main.go
By default, like "helm list", only deployed and failed statuses are returned. If you want all releases statuses, like "helm list --all", you need this fix.
#117
> Fix to get all releases statuses and not only deployed/failed (default)

- Dockerfile
Currently the latest docker image of helm-exporter is built with alpine 3.18.2 which has multiple critical security vulnerabilities (busybox, ssl_client). Pinning the alpine version to the latest 3.18 release fixes those vulnerabilities
> pins alpine version to latest 3.18.x
